Fix build with NDEBUG defined
Build with NDEBUG fails because the debug() macro becomes empty. This
creates invalid syntax with the debug() call is the only statement in
the body of a 'for' loop.

This fixes build failures like:

daemon.c: In function 'show':
daemon.c:3607:2: error: expected expression before '}' token
  }
  ^